[tool.isort]
profile = "black"

[tool.black]
target-version = ["py38", "py39", "py310", "py311"]

preview = true

[tool.flake8]
max-line-length = 88
extend-select = "B950"
extend-ignore = ["E203", "E501", "E701"]
